### ISSUE TITLE
コメントアウト

### ISSUE THREAD

**Issue by soukouki** [lriki/Lumino#2]
たくさんの場所でコードのコメントアウトがありますが、gitを使っているんですからそっちに任せませんか？

**Comment by lriki** [comment]
今は身内向けに、動くものを用意するのを最優先にしています。
そのためコードが書き散らかされていてものすごく汚くなっているのは承知してます。
ゆくゆくは整理したいのですが、すぐはちょっと厳しいです。

**Comment by soukouki** [comment]
わかりました。

**Comment by soukouki** [comment]
そのコードはこちらで消してもいいですか？

**Comment by lriki** [comment]
1行だけぽつんとコメントアウトされてるようなものや、他で使われてそうにない関数定義がコメントアウトされているようなのは、ほとんど消しても大丈夫です。
ただ、周辺に TODO コメントがあったり、かなり長いコードが #if 0～#endif で囲まれているものはドラフトコードだったりするので避けてもらえると良いかと思います。

**Comment by soukouki** [comment]
戻すのを忘れてかなり前のコードが残っていた。ということはないのですか？

**Comment by lriki** [comment]
それもあると思います。実際見てみないと何とも言えませんからね・・・。

**Comment by lriki** [comment]
いったんCloseします。リファクタリングと併せて随時行っていきます。
