### ISSUE TITLE
ビルドができない

### ISSUE THREAD

**Issue by soukouki** [lriki/Lumino#4]
cmakeをインストールしてbuild_msvcを実行したのですが

C:\_prog\Lumino\build_vs2015_u>cmake ".." -G "Visual Studio 14 2015" -DLN_USE_UNICODE_CHAR_SET=ON
CMake Error at CMakeLists.txt:749 (add_subdirectory):
  The source directory

    C:/_prog/Lumino/external/Lumino.Core

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:750 (add_subdirectory):
  The source directory

    C:/_prog/Lumino/external/Lumino.Math

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:753 (ln_make_postfix):
  Unknown CMake command "ln_make_postfix".

-- Configuring incomplete, errors occurred!
See also "C:/_prog/Lumino/build_vs2015_u/CMakeFiles/CMakeOutput.log".

C:\_prog\Lumino\build_vs2015_u>MSBuild ".\Lumino.sln" /t:Rebuild /p:Configuration="Release" /p:Platf
orm="Win32" /m
Microsoft (R) Build Engine バージョン 4.6.1055.0
[Microsoft .NET Framework、バージョン 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: プロジェクト ファイルが存在しません。
スイッチ:.\Lumino.sln

と出てしまいビルドができません。

**Comment by lriki** [comment]
git clone した後、サブモジュールもすべて取得されているか確認してみてください。
Lumino は Lumino.Core と Lumino.Math にサブモジュールを使って依存しています。
※[Download ZIP] ボタンから落とした一式ではビルドできません。

**Comment by soukouki** [comment]
ありがとうございます。
